# Generated by Django 3.0.3 on 2020-02-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dues_Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=50)),
                ('dues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Dues_Option')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Type_Payment')),
            ],
        ),
    ]
