# Generated by Django 3.0.3 on 2020-02-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dues_option',
            name='value',
            field=models.IntegerField(),
        ),
    ]
