# Generated by Django 3.0.3 on 2020-02-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200209_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dues_option',
            name='code',
        ),
    ]
