# Generated by Django 3.0.3 on 2020-02-09 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_payment'),
        ('payments', '0005_dues_option_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
            preserve_default=False,
        ),
    ]
