# Generated by Django 3.0.3 on 2020-02-09 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='dues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Dues_Option'),
        ),
    ]
