# Generated by Django 3.0.3 on 2020-02-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payment',
        ),
    ]
